# Generated by Django 3.1.1 on 2021-11-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_ranger',
            field=models.BooleanField(default=False),
        ),
    ]
