# Generated by Django 3.1.1 on 2021-11-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20211129_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='useravatar.png', upload_to='media'),
        ),
    ]
