# Generated by Django 3.2.5 on 2021-09-13 08:15

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210909_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='Image')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(related_name='products', to='blog.Image'),
        ),
    ]
