# Generated by Django 3.2.5 on 2021-09-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210913_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(default='default.png', related_name='products', to='blog.Image'),
        ),
    ]
