# Generated by Django 3.2.5 on 2021-09-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(default='default.jpg', related_name='products', to='blog.Image'),
        ),
    ]
