# Generated by Django 3.2.5 on 2021-09-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210914_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_ppoi',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(to='blog.Image'),
        ),
    ]
