# Generated by Django 3.2.5 on 2021-09-14 07:03

from django.db import migrations, models
import django.utils.timezone
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210914_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(related_name='products', to='blog.Image'),
        ),
    ]
