# Generated by Django 3.2.5 on 2021-09-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210914_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
