# Generated by Django 3.2.5 on 2021-09-14 07:17

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='media/default.jpg', upload_to='images/', verbose_name='Image'),
        ),
    ]
