# Generated by Django 3.2.5 on 2021-09-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_ppoi',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
