# Generated by Django 3.1.1 on 2021-11-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_post_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='itemcategory',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
